name: urban_flooding
description: "A Digital Twin Approach to Reducing the Impacts of Urban Flooding."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_svg: ^2.2.0
  fl_chart: ^1.1.0
  http: ^1.5.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/assets/
  - .env
  
