name: urban_flooding
description: "A Digital Twin Approach to Reducing the Impacts of Urban Flooding."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_svg: ^2.0.7
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/black_swan_logo.svg
    - lib/assets/weather_cloudy.svg
    - lib/assets/weather_sunny.svg
    - lib/assets/weather_rainy.svg
